// This file is automatically generated by the Makefile - DO NOT EDIT!
// You can (should) also tell mercurial to ignore it.

#ifndef _VERSION_
#define _VERSION_

#define VERSION "4.2.286"
#define VERSION_SUFFIX ""
#define TAGDISTANCE 286
#define CACHEFOLDERNAME "RawTherapee"

#endif

