//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public enum ActionCode {
  AC_DONTWRITE,
  AC_WRITE,
  AC_SYSTEM,
  AC_NEW,
  AC_INVALID = 100
}

}
