//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class BatchProcessingListener : ProgressListener {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BatchProcessingListener(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libPhotoAssistantImageProcessingPINVOKE.BatchProcessingListener_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BatchProcessingListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BatchProcessingListener() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_BatchProcessingListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual ProcessingJob imageReady(IImage16 img) {
    global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.BatchProcessingListener_imageReady(swigCPtr, IImage16.getCPtr(img));
    ProcessingJob ret = (cPtr == global::System.IntPtr.Zero) ? null : new ProcessingJob(cPtr, false);
    return ret;
  }

  public override void error(string message) {
    libPhotoAssistantImageProcessingPINVOKE.BatchProcessingListener_error(swigCPtr, message);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
