//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class CoarseTransformParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CoarseTransformParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CoarseTransformParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CoarseTransformParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_CoarseTransformParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int rotate {
    set {
      libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_rotate_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_rotate_get(swigCPtr);
      return ret;
    } 
  }

  public bool hflip {
    set {
      libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_hflip_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_hflip_get(swigCPtr);
      return ret;
    } 
  }

  public bool vflip {
    set {
      libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_vflip_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_vflip_get(swigCPtr);
      return ret;
    } 
  }

  public CoarseTransformParams() : this(libPhotoAssistantImageProcessingPINVOKE.new_CoarseTransformParams(), true) {
  }

  public void setDefaults() {
    libPhotoAssistantImageProcessingPINVOKE.CoarseTransformParams_setDefaults(swigCPtr);
  }

}

}
