//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class Coord2D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Coord2D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Coord2D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Coord2D() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_Coord2D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double x {
    set {
      libPhotoAssistantImageProcessingPINVOKE.Coord2D_x_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.Coord2D_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      libPhotoAssistantImageProcessingPINVOKE.Coord2D_y_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.Coord2D_y_get(swigCPtr);
      return ret;
    } 
  }

  public Coord2D(double x_, double y_) : this(libPhotoAssistantImageProcessingPINVOKE.new_Coord2D__SWIG_0(x_, y_), true) {
  }

  public Coord2D() : this(libPhotoAssistantImageProcessingPINVOKE.new_Coord2D__SWIG_1(), true) {
  }

  public void set(double x_, double y_) {
    libPhotoAssistantImageProcessingPINVOKE.Coord2D_set(swigCPtr, x_, y_);
  }

}

}
