//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class EPDParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EPDParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EPDParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EPDParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_EPDParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool enabled {
    set {
      libPhotoAssistantImageProcessingPINVOKE.EPDParams_enabled_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.EPDParams_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public double strength {
    set {
      libPhotoAssistantImageProcessingPINVOKE.EPDParams_strength_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.EPDParams_strength_get(swigCPtr);
      return ret;
    } 
  }

  public double gamma {
    set {
      libPhotoAssistantImageProcessingPINVOKE.EPDParams_gamma_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.EPDParams_gamma_get(swigCPtr);
      return ret;
    } 
  }

  public double edgeStopping {
    set {
      libPhotoAssistantImageProcessingPINVOKE.EPDParams_edgeStopping_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.EPDParams_edgeStopping_get(swigCPtr);
      return ret;
    } 
  }

  public double scale {
    set {
      libPhotoAssistantImageProcessingPINVOKE.EPDParams_scale_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.EPDParams_scale_get(swigCPtr);
      return ret;
    } 
  }

  public int reweightingIterates {
    set {
      libPhotoAssistantImageProcessingPINVOKE.EPDParams_reweightingIterates_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.EPDParams_reweightingIterates_get(swigCPtr);
      return ret;
    } 
  }

  public EPDParams() : this(libPhotoAssistantImageProcessingPINVOKE.new_EPDParams(), true) {
  }

}

}
