//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class ImageMatrices : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImageMatrices(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageMatrices obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageMatrices() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_ImageMatrices(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_a_3__double rgb_cam {
    set {
      libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_rgb_cam_set(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_rgb_cam_get(swigCPtr);
      SWIGTYPE_p_a_3__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_a_3__double cam_rgb {
    set {
      libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_cam_rgb_set(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_cam_rgb_get(swigCPtr);
      SWIGTYPE_p_a_3__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_a_3__double xyz_cam {
    set {
      libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_xyz_cam_set(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_xyz_cam_get(swigCPtr);
      SWIGTYPE_p_a_3__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_a_3__double cam_xyz {
    set {
      libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_cam_xyz_set(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.ImageMatrices_cam_xyz_get(swigCPtr);
      SWIGTYPE_p_a_3__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
      return ret;
    } 
  }

  public ImageMatrices() : this(libPhotoAssistantImageProcessingPINVOKE.new_ImageMatrices(), true) {
  }

}

}
