//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class Image8 : IImage8 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Image8(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libPhotoAssistantImageProcessingPINVOKE.Image8_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Image8 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Image8() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_Image8(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Image8() : this(libPhotoAssistantImageProcessingPINVOKE.new_Image8__SWIG_0(), true) {
  }

  public Image8(int width, int height) : this(libPhotoAssistantImageProcessingPINVOKE.new_Image8__SWIG_1(width, height), true) {
  }

  public Image8 copy() {
    global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.Image8_copy(swigCPtr);
    Image8 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Image8(cPtr, false);
    return ret;
  }

  public virtual string getType() {
    string ret = libPhotoAssistantImageProcessingPINVOKE.Image8_getType(swigCPtr);
    return ret;
  }

  public virtual int getBPS() {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_getBPS(swigCPtr);
    return ret;
  }

  public virtual void getScanline(int row, SWIGTYPE_p_unsigned_char buffer, int bps) {
    libPhotoAssistantImageProcessingPINVOKE.Image8_getScanline(swigCPtr, row, SWIGTYPE_p_unsigned_char.getCPtr(buffer), bps);
  }

  public virtual void setScanline(int row, SWIGTYPE_p_unsigned_char buffer, int bps, SWIGTYPE_p_float minValue, SWIGTYPE_p_float maxValue) {
    libPhotoAssistantImageProcessingPINVOKE.Image8_setScanline__SWIG_0(swigCPtr, row, SWIGTYPE_p_unsigned_char.getCPtr(buffer), bps, SWIGTYPE_p_float.getCPtr(minValue), SWIGTYPE_p_float.getCPtr(maxValue));
  }

  public virtual void setScanline(int row, SWIGTYPE_p_unsigned_char buffer, int bps, SWIGTYPE_p_float minValue) {
    libPhotoAssistantImageProcessingPINVOKE.Image8_setScanline__SWIG_1(swigCPtr, row, SWIGTYPE_p_unsigned_char.getCPtr(buffer), bps, SWIGTYPE_p_float.getCPtr(minValue));
  }

  public virtual void setScanline(int row, SWIGTYPE_p_unsigned_char buffer, int bps) {
    libPhotoAssistantImageProcessingPINVOKE.Image8_setScanline__SWIG_2(swigCPtr, row, SWIGTYPE_p_unsigned_char.getCPtr(buffer), bps);
  }

  public override MyMutex getMutex() {
    MyMutex ret = new MyMutex(libPhotoAssistantImageProcessingPINVOKE.Image8_getMutex(swigCPtr), false);
    return ret;
  }

  public override SWIGTYPE_p_cmsHPROFILE getProfile() {
    SWIGTYPE_p_cmsHPROFILE ret = new SWIGTYPE_p_cmsHPROFILE(libPhotoAssistantImageProcessingPINVOKE.Image8_getProfile(swigCPtr), true);
    return ret;
  }

  public override int getBitsPerPixel() {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_getBitsPerPixel(swigCPtr);
    return ret;
  }

  public override int saveToFile(string fname) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveToFile(swigCPtr, fname);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsPNG(string fname, int compression, int bps) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsPNG__SWIG_0(swigCPtr, fname, compression, bps);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsPNG(string fname, int compression) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsPNG__SWIG_1(swigCPtr, fname, compression);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsPNG(string fname) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsPNG__SWIG_2(swigCPtr, fname);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsJPEG(string fname, int quality, int subSamp) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsJPEG__SWIG_0(swigCPtr, fname, quality, subSamp);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsJPEG(string fname, int quality) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsJPEG__SWIG_1(swigCPtr, fname, quality);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsJPEG(string fname) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsJPEG__SWIG_2(swigCPtr, fname);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsTIFF(string fname, int bps, bool uncompressed) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsTIFF__SWIG_0(swigCPtr, fname, bps, uncompressed);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsTIFF(string fname, int bps) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsTIFF__SWIG_1(swigCPtr, fname, bps);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int saveAsTIFF(string fname) {
    int ret = libPhotoAssistantImageProcessingPINVOKE.Image8_saveAsTIFF__SWIG_2(swigCPtr, fname);
    if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void setSaveProgressListener(ProgressListener pl) {
    libPhotoAssistantImageProcessingPINVOKE.Image8_setSaveProgressListener(swigCPtr, ProgressListener.getCPtr(pl));
  }

  public override void free() {
    libPhotoAssistantImageProcessingPINVOKE.Image8_free(swigCPtr);
  }

}

}
