//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class MyRWMutex : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MyRWMutex(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MyRWMutex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MyRWMutex() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_MyRWMutex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint writerCount {
    set {
      libPhotoAssistantImageProcessingPINVOKE.MyRWMutex_writerCount_set(swigCPtr, value);
    } 
    get {
      uint ret = libPhotoAssistantImageProcessingPINVOKE.MyRWMutex_writerCount_get(swigCPtr);
      return ret;
    } 
  }

  public uint readerCount {
    set {
      libPhotoAssistantImageProcessingPINVOKE.MyRWMutex_readerCount_set(swigCPtr, value);
    } 
    get {
      uint ret = libPhotoAssistantImageProcessingPINVOKE.MyRWMutex_readerCount_get(swigCPtr);
      return ret;
    } 
  }

  public MyRWMutex() : this(libPhotoAssistantImageProcessingPINVOKE.new_MyRWMutex(), true) {
  }

}

}
