//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class PCVignetteParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PCVignetteParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PCVignetteParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PCVignetteParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_PCVignetteParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool enabled {
    set {
      libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_enabled_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public double strength {
    set {
      libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_strength_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_strength_get(swigCPtr);
      return ret;
    } 
  }

  public int feather {
    set {
      libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_feather_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_feather_get(swigCPtr);
      return ret;
    } 
  }

  public int roundness {
    set {
      libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_roundness_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.PCVignetteParams_roundness_get(swigCPtr);
      return ret;
    } 
  }

  public PCVignetteParams() : this(libPhotoAssistantImageProcessingPINVOKE.new_PCVignetteParams(), true) {
  }

}

}
