//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class SharpenEdgeParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SharpenEdgeParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SharpenEdgeParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SharpenEdgeParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_SharpenEdgeParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool enabled {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_enabled_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public int passes {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_passes_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_passes_get(swigCPtr);
      return ret;
    } 
  }

  public double amount {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_amount_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_amount_get(swigCPtr);
      return ret;
    } 
  }

  public bool threechannels {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_threechannels_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.SharpenEdgeParams_threechannels_get(swigCPtr);
      return ret;
    } 
  }

  public SharpenEdgeParams() : this(libPhotoAssistantImageProcessingPINVOKE.new_SharpenEdgeParams(), true) {
  }

}

}
