//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class SHParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SHParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SHParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SHParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_SHParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool enabled {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_enabled_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_enabled_get(swigCPtr);
      return ret;
    } 
  }

  public bool hq {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_hq_set(swigCPtr, value);
    } 
    get {
      bool ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_hq_get(swigCPtr);
      return ret;
    } 
  }

  public int highlights {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_highlights_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_highlights_get(swigCPtr);
      return ret;
    } 
  }

  public int htonalwidth {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_htonalwidth_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_htonalwidth_get(swigCPtr);
      return ret;
    } 
  }

  public int shadows {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_shadows_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_shadows_get(swigCPtr);
      return ret;
    } 
  }

  public int stonalwidth {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_stonalwidth_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_stonalwidth_get(swigCPtr);
      return ret;
    } 
  }

  public int localcontrast {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_localcontrast_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_localcontrast_get(swigCPtr);
      return ret;
    } 
  }

  public int radius {
    set {
      libPhotoAssistantImageProcessingPINVOKE.SHParams_radius_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.SHParams_radius_get(swigCPtr);
      return ret;
    } 
  }

  public SHParams() : this(libPhotoAssistantImageProcessingPINVOKE.new_SHParams(), true) {
  }

}

}
