//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public enum ThFileType {
  FT_Invalid = -1,
  FT_None = 0,
  FT_Raw = 1,
  FT_Jpeg = 2,
  FT_Tiff = 3,
  FT_Png = 4,
  FT_Custom = 5,
  FT_Tiff16 = 6,
  FT_Png16 = 7,
  FT_Custom16 = 8
}

}
