//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class TIFFHeader : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TIFFHeader(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TIFFHeader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TIFFHeader() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_TIFFHeader(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ushort byteOrder {
    set {
      libPhotoAssistantImageProcessingPINVOKE.TIFFHeader_byteOrder_set(swigCPtr, value);
    } 
    get {
      ushort ret = libPhotoAssistantImageProcessingPINVOKE.TIFFHeader_byteOrder_get(swigCPtr);
      return ret;
    } 
  }

  public ushort _fixed {
    set {
      libPhotoAssistantImageProcessingPINVOKE.TIFFHeader__fixed_set(swigCPtr, value);
    } 
    get {
      ushort ret = libPhotoAssistantImageProcessingPINVOKE.TIFFHeader__fixed_get(swigCPtr);
      return ret;
    } 
  }

  public uint ifdOffset {
    set {
      libPhotoAssistantImageProcessingPINVOKE.TIFFHeader_ifdOffset_set(swigCPtr, value);
    } 
    get {
      uint ret = libPhotoAssistantImageProcessingPINVOKE.TIFFHeader_ifdOffset_get(swigCPtr);
      return ret;
    } 
  }

  public TIFFHeader() : this(libPhotoAssistantImageProcessingPINVOKE.new_TIFFHeader(), true) {
  }

}

}
