//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public class WBParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WBParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WBParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~WBParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libPhotoAssistantImageProcessingPINVOKE.delete_WBParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static SWIGTYPE_p_std__vectorT_rtengine__procparams__WBEntry_p_t wbEntries {
    set {
      libPhotoAssistantImageProcessingPINVOKE.WBParams_wbEntries_set(SWIGTYPE_p_std__vectorT_rtengine__procparams__WBEntry_p_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libPhotoAssistantImageProcessingPINVOKE.WBParams_wbEntries_get();
      SWIGTYPE_p_std__vectorT_rtengine__procparams__WBEntry_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_rtengine__procparams__WBEntry_p_t(cPtr, false);
      return ret;
    } 
  }

  public string method {
    set {
      libPhotoAssistantImageProcessingPINVOKE.WBParams_method_set(swigCPtr, value);
      if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = libPhotoAssistantImageProcessingPINVOKE.WBParams_method_get(swigCPtr);
      if (libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Pending) throw libPhotoAssistantImageProcessingPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int temperature {
    set {
      libPhotoAssistantImageProcessingPINVOKE.WBParams_temperature_set(swigCPtr, value);
    } 
    get {
      int ret = libPhotoAssistantImageProcessingPINVOKE.WBParams_temperature_get(swigCPtr);
      return ret;
    } 
  }

  public double green {
    set {
      libPhotoAssistantImageProcessingPINVOKE.WBParams_green_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.WBParams_green_get(swigCPtr);
      return ret;
    } 
  }

  public double equal {
    set {
      libPhotoAssistantImageProcessingPINVOKE.WBParams_equal_set(swigCPtr, value);
    } 
    get {
      double ret = libPhotoAssistantImageProcessingPINVOKE.WBParams_equal_get(swigCPtr);
      return ret;
    } 
  }

  public static void init() {
    libPhotoAssistantImageProcessingPINVOKE.WBParams_init();
  }

  public static void cleanup() {
    libPhotoAssistantImageProcessingPINVOKE.WBParams_cleanup();
  }

  public WBParams() : this(libPhotoAssistantImageProcessingPINVOKE.new_WBParams(), true) {
  }

}

}
