//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhotoAssistant.Indexer.Wrappers {

public enum WBTypes {
  WBT_CAMERA,
  WBT_AUTO,
  WBT_DAYLIGHT,
  WBT_CLOUDY,
  WBT_SHADE,
  WBT_WATER,
  WBT_TUNGSTEN,
  WBT_FLUORESCENT,
  WBT_LAMP,
  WBT_FLASH,
  WBT_LED,
  WBT_CUSTOM
}

}
