SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER_INIT x86_64-w64-mingw32-windres)

SET(QT_MOC_EXECUTABLE /c/msys64/mingw64/bin/moc)
SET(QT_RCC_EXECUTABLE /c/msys64/mingw64/bin/rcc)
SET(QT_UIC_EXECUTABLE /c/msys64/mingw64/bin/uic)

SET(CMAKE_SYSTEM_PROGRAM_PATH ./Builds/Debug/bin)
SET(CMAKE_FIND_ROOT_PATH /c/msys64/mingw64)
SET(CMAKE_INSTALL_PREFIX /c/msys64/mingw64)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(INSTALL install)
